# Workflow
name: HTML&CSS Course Assignment

# Where do the workflow run
on:
  # Push request
  push:
    # Push to main branch
    branches: ["main"]

  # PR Request
  pull_request:
    # PR to main branch
    branches: ["main"]

  # Allow you to run this workflow manually from GitHub in the Actions tab
  workflow_dispatch:
# Run on which Jobs
